name:  Dispatch
uses: peter-evans/repository-dispatch@v1
with:
  token: ${{ secrets.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 }}
  repository: VladPluhin/ethnocontemporaryballet
  event-type: my-event
  client-payload: '{"key1": "value1", "key2": "value2"}'